version: '3.8'

networks:
  internal-network:

services:

  mysql-db:
    image: mysql:latest
    networks:
      internal-network:

    container_name: mysql-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'periscope'

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    #    container_name: kafka
    networks:
      internal-network:
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    #    container_name: zookeeper
    networks:
      internal-network:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64


  spring-app:
    #    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    #    image: moonbse/backend:latest
    platform: linux/amd64
    networks:
      internal-network:

    depends_on:
      #      - kafka
      - mysql-db
    ports:
      - "8082:8082"








