package com.app.models.canvas;

import java.util.ArrayList;
import java.util.List;
public class Object{
    public String type;
    public String version;
    public String originX;
    public String originY;
    public double left;
    public double top;
    public double width;
    public double height;
    public String fill;
    public String stroke;
    public int strokeWidth;
    public Object strokeDashArray;
    public String strokeLineCap;
    public int strokeDashOffset;
    public String strokeLineJoin;
    public boolean strokeUniform;
    public int strokeMiterLimit;
    public int scaleX;
    public int scaleY;
    public int angle;
    public boolean flipX;
    public boolean flipY;
    public int opacity;
    public Object shadow;
    public boolean visible;
    public String backgroundColor;
    public String fillRule;
    public String paintFirst;
    public String globalCompositeOperation;
    public int skewX;
    public int skewY;
    public String id;
    public ArrayList<Object> objects;
    public ArrayList<Connection> connections;
    public double x1;
    public double x2;
    public double y1;
    public double y2;
    public int cropX;
    public int cropY;
    public String src;
    public Object crossOrigin;
    public ArrayList<Object> filters;
}
